name: UserService Integration

on: [push, pull_request]

env:
  SERVICE_NAME: user

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ env.SERVICE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Lint with Gradle
        run: ./gradlew ktlintCheck
      - name: Run dependency with Gradle
        run: ./gradlew dockerRun
      - name: Test with Gradle
        run: ./gradlew test
      - name: Stop dependency with Gradle
        run: ./gradlew dockerStop
